### ISSUE TITLE
Usando markdown.

### ISSUE THREAD

**Issue by MizaelBR** [iurygdeoliveira/iurygdeoliveira#6]
## Duvida sobre seu Readme.md
Gostaria de saber se tem algum motivo o senhor ter colocado os links das suas redes sociais em html se tem como usar em markdown? 

Eu Fiz um exemplo de como fica em markdown.

### HTML:
<ul>
  <li>
    <img src="https://user-images.githubusercontent.com/30157522/87162006-b6c05980-c29b-11ea-8dfe-fba74549729b.png" width="18" alt="Youtube">
    <a href="https://www.youtube.com/channel/UCTM1Idirf0ALOdEdq31qkjg?view_as=subscriber" target="_blank" title="My Youtube">Youtube</a>
  </li>
  <li>
    <img src="https://user-images.githubusercontent.com/30157522/87161461-f33f8580-c29a-11ea-8686-34eb06e44501.png" width="18" alt="Twitter"> 
    <a href="https://twitter.com/IuryProf" target="_blank" title="My Twitter">Twitter</a>
  </li>
  <li>
    <img src="https://user-images.githubusercontent.com/30157522/87161827-6cd77380-c29b-11ea-902a-725eeed60745.png" width="18" alt="Linkedin"> 
    <a href="https://www.linkedin.com/in/iurygdeoliveira/" target="_blank" title="My LinkedIn">LinkedIn</a>
  </li>
</ul>

```html
<ul>
  <li>
    <img src="https://user-images.githubusercontent.com/30157522/87162006-b6c05980-c29b-11ea-8dfe-fba74549729b.png" width="18" alt="Youtube">
    <a href="https://www.youtube.com/channel/UCTM1Idirf0ALOdEdq31qkjg?view_as=subscriber" target="_blank" title="My Youtube">Youtube</a>
  </li>
  <li>
    <img src="https://user-images.githubusercontent.com/30157522/87161461-f33f8580-c29a-11ea-8686-34eb06e44501.png" width="18" alt="Twitter"> 
    <a href="https://twitter.com/IuryProf" target="_blank" title="My Twitter">Twitter</a>
  </li>
  <li>
    <img src="https://user-images.githubusercontent.com/30157522/87161827-6cd77380-c29b-11ea-902a-725eeed60745.png" width="18" alt="Linkedin"> 
    <a href="https://www.linkedin.com/in/iurygdeoliveira/" target="_blank" title="My LinkedIn">LinkedIn</a>
  </li>
</ul>
```

### Markdown:
- <img src="https://user-images.githubusercontent.com/30157522/87162006-b6c05980-c29b-11ea-8dfe-fba74549729b.png" width="18" alt="Youtube"> [Youtube](https://www.youtube.com/channel/UCTM1Idirf0ALOdEdq31qkjg?view_as=subscriber)
- <img src="https://user-images.githubusercontent.com/30157522/87161461-f33f8580-c29a-11ea-8686-34eb06e44501.png" width="18" alt="Twitter"> [Twitter](https://twitter.com/IuryProf)
- <img src="https://user-images.githubusercontent.com/30157522/87161827-6cd77380-c29b-11ea-902a-725eeed60745.png" width="18" alt="Linkedin"> [LinkedIn](https://www.linkedin.com/in/iurygdeoliveira/)

```md
- <img src="https://user-images.githubusercontent.com/30157522/87162006-b6c05980-c29b-11ea-8dfe-fba74549729b.png" width="18" alt="Youtube"> [Youtube](https://www.youtube.com/channel/UCTM1Idirf0ALOdEdq31qkjg?view_as=subscriber)
- <img src="https://user-images.githubusercontent.com/30157522/87161461-f33f8580-c29a-11ea-8686-34eb06e44501.png" width="18" alt="Twitter"> [Twitter](https://twitter.com/IuryProf)
- <img src="https://user-images.githubusercontent.com/30157522/87161827-6cd77380-c29b-11ea-902a-725eeed60745.png" width="18" alt="Linkedin"> [LinkedIn](https://www.linkedin.com/in/iurygdeoliveira/)
```

**Comment by iurygdeoliveira** [comment]
@mizaelc 

Utilizei html para facilidade, de posicionar os elementos, acho mais fácil do que markdown
