### ISSUE TITLE
Professor não estou conseguindo produzir com o conteúdo do curso 

### ISSUE THREAD

**Issue by thomasheenry** [iurygdeoliveira/iurygdeoliveira#7]
Eu sou iniciante no ramo de programação, portanto eu não sei muita coisa e estou ficando confuso com todo esse conteúdo, o senhor pode me ajudar por onde começar e focar?

**Comment by iurygdeoliveira** [comment]
@BastleH posso sim, quais as dúvidas ?

**Comment by thomasheenry** [comment]
Na hora de instalar o Docker da erro, vou tentar ver uns tutoriais aqui no youtube

**Comment by iurygdeoliveira** [comment]
Utilizar as issues do novos caminhos: https://github.com/iurygdeoliveira/novos_caminhos/issues
