### ISSUE TITLE
Estrutura de desenvolvimento 

### ISSUE THREAD

**Issue by Agenildo** [iurygdeoliveira/iurygdeoliveira#8]
Prezado Iury
Dúvida:
A minha estrutura de desenvolvimento no vscode, deve ter as mesmas pastas que as mostradas no vídeo?
a saber: novos caminhos/
              02/

**Comment by iurygdeoliveira** [comment]
@Agenildo Tecnicamente não, 

Essa pasta é apenas para irmos deixando salvo os trabalhos que já foram realizados.
